# Generated by Django 5.0 on 2023-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=500)),
                ('Category', models.IntegerField(choices=[(1, 'Mobile'), (2, 'clothes'), (3, 'shoes')])),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
